language: ruby
rvm:
  - 2.1.0
  - jruby
cache: bundler
script: bundle exec ruby -r 'minitest/autorun' test/*.rb

notifications:
  flowdock:
    secure: "U+2YE+aQNFXeD3Ff4indCT6fGRpkYITgXfXRRL/SeBQwMggZDl4SCiVJ9MMiMsXkbv1z8dhpZNAfGvM0473SOZel3gVEczMi/UVOYyLJnC+fElvm9cTnnYwsJ6hf+Fn76dyvac7J6lSb0cq50VlFhsyWfyy+/H0eF93+FVKsUv4="
